### ISSUE TITLE
Deliver sum of style rules per language

### ISSUE THREAD

**Issue by p-goulart** [languagetooler-gmbh/rule-creation-stats#16]
Right now we only have a summary breakdown per tone tag, we also need a sum.

**Comment by affemitkaraffe** [comment]
@marshinkar , if we add up the tone tags, we get the sum of tone tags assigned to rules. But: Since we have rules with multiple tone tags, the sum would not be equal to the number of style rules in the files. Is that what you want? Or rather the number of style rules in the files?
